name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Install
        run: yarn

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn test --if-present

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
